print("=" * 50)
print("Evaluación N°1 Redes Virtualizadas")
print("=" * 50)
print("Integrantes: Juan Farias Rojas")
print("             Matias Guimay Trimpai ")
print("             Karin Gutierrez Alarcon ")
print("Asignatura: Redes Virtuales")
print("Código-sección: 50")
print("Sede: Republica Online")
print("=" * 50)
