echo "=========================================="
echo "Evaluación N°1 - Redes Virtualizadas"
echo "Script ejecutado correctamente"
echo "=========================================="
echo "Usuario que ejecuta el script: $(whoami)"
echo "Nombre del equipo: $(hostname)"
echo "Directorio actual: $(pwd)"
echo "Fecha y hora: $(date)"
echo "=========================================="
